### ISSUE TITLE
Plotting

### ISSUE THREAD

**Issue by ricardofrantz** [jcanton/pipeMeshNek#2]
Hey Jacopo,

I am trying to use the _pymech_ suite to read output binary files from _nek_ in order to plot velocity fields, perform integrals and data analysis on simulations. I am able to read the output file following the examples: field = ns.readnek( 'channel3D_0.f00001'). The closest I could get is your plotMesh.py script, the reason I am posting this here. Considering I am using the re2 mesh file. Could you please share a similar example of a velocity field plot with matplolib? Thanks in advance

**Comment by jcanton** [comment]
Hey Ricardo,
plotMesh.py is not intended for plotting actual velocity fields, it is intended just for testing the mesh generator in pipeMeshNek. And pymech does not provide routines for plotting because we actually never used it for that but just for data analysis / postprocessing.
I normally use visit or paraview for plotting so I am sorry but I think I cannot help you with this.
Regards,
Jacopo
